-- ── DATABASE SETUP: BANK SOAL & JADWAL AI ──
-- Tanggal: 27 April 2026

-- 1. Tabel Questions (Bank Soal dari Guru)
CREATE TABLE IF NOT EXISTS public.questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    teacher_id UUID REFERENCES auth.users(id),
    subject TEXT NOT NULL, -- Contoh: 'Matematika', 'Biologi', 'SNBT'
    topic TEXT NOT NULL,   -- Contoh: 'Turunan', 'Sel', 'Penalaran Umum'
    question_text TEXT NOT NULL,
    image_url TEXT, -- Opsional, jika soal ada gambarnya (diagram/grafik)
    options JSONB NOT NULL, -- Format: {"A": "isi", "B": "isi", ...}
    correct_option TEXT NOT NULL, -- Contoh: 'A'
    difficulty TEXT CHECK (difficulty IN ('Easy', 'Medium', 'Hard')) DEFAULT 'Medium',
    explanation TEXT, -- Pembahasan soal
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel School Schedules (Hasil Scan Jadwal AI)
CREATE TABLE IF NOT EXISTS public.school_schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    day TEXT NOT NULL, -- Contoh: 'Senin', 'Selasa', ...
    subject TEXT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Daily Missions (Rencana Belajar Harian generated by AI)
CREATE TABLE IF NOT EXISTS public.daily_missions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    mission_date DATE DEFAULT CURRENT_DATE,
    title TEXT NOT NULL,
    description TEXT,
    subject TEXT,
    is_completed BOOLEAN DEFAULT FALSE,
    points_reward INT DEFAULT 50,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── SECURITY (Row Level Security) ──

-- Aktifkan RLS
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_missions ENABLE ROW LEVEL SECURITY;

-- Polisi untuk Questions (Siswa bisa baca semua, Guru bisa edit miliknya)
CREATE POLICY "Siswa bisa melihat semua soal" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Guru bisa tambah soal" ON public.questions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Guru bisa edit soal milik sendiri" ON public.questions FOR UPDATE USING (auth.uid() = teacher_id);

-- Polisi untuk Jadwal (User hanya bisa akses miliknya sendiri)
CREATE POLICY "User bisa kelola jadwal sendiri" ON public.school_schedules 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);

-- Polisi untuk Misi Harian (User hanya bisa akses miliknya sendiri)
CREATE POLICY "User bisa kelola misi sendiri" ON public.daily_missions 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);

-- ── REALTIME ──
-- Aktifkan realtime untuk Daily Missions agar progress langsung terupdate di aplikasi
ALTER PUBLICATION supabase_realtime ADD TABLE daily_missions;
