// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoj040EpcI5uoduqJRowskbFLqS-0nFoE',
    appId: '1:872654052950:web:9fef1c4864a2331faca5f7',
    messagingSenderId: '872654052950',
    projectId: 'study-buddy-connectors',
    authDomain: 'study-buddy-connectors.firebaseapp.com',
    storageBucket: 'study-buddy-connectors.firebasestorage.app',
    measurementId: 'G-VLDVJTX2W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDYWTiXS7nOZxtLRp5M9CunqfduiyiS0',
    appId: '1:872654052950:android:48329bcf081233d3aca5f7',
    messagingSenderId: '872654052950',
    projectId: 'study-buddy-connectors',
    storageBucket: 'study-buddy-connectors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOi1LreivTj6OibHt8QkrE4ms4bfz-sA',
    appId: '1:872654052950:ios:255cafdaf0e9d899aca5f7',
    messagingSenderId: '872654052950',
    projectId: 'study-buddy-connectors',
    storageBucket: 'study-buddy-connectors.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOi1LreivTj6OibHt8QkrE4ms4bfz-sA',
    appId: '1:872654052950:ios:255cafdaf0e9d899aca5f7',
    messagingSenderId: '872654052950',
    projectId: 'study-buddy-connectors',
    storageBucket: 'study-buddy-connectors.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoj040EpcI5uoduqJRowskbFLqS-0nFoE',
    appId: '1:872654052950:web:e255f0fb25bf1b8daca5f7',
    messagingSenderId: '872654052950',
    projectId: 'study-buddy-connectors',
    authDomain: 'study-buddy-connectors.firebaseapp.com',
    storageBucket: 'study-buddy-connectors.firebasestorage.app',
    measurementId: 'G-70ND01W8CZ',
  );
}
